#!/bin/sh

# PROJECT_DIR y BASE_URL deben establecerse antes de
# llamar el script en el cron

TMP_OUTPUT=/tmp/dumbu_scheduler

SCHED_URL=$BASE_URL/index.php/scheduler
SCHED_SPECIAL_URL=$BASE_URL/index.php/scheduler/special

SCHED_LOG=$PROJECT_DIR/var/messages.log

HTTP_PROXY=""
HTTPS_PROXY=""

SESSIONS_DIR=$PROJECT_DIR/vendor/mgp25/instagram-php/sessions/

/usr/bin/wget -O $TMP_OUTPUT $SCHED_URL && cat $TMP_OUTPUT >> $SCHED_LOG && rm $TMP_OUTPUT
sleep 10
/usr/bin/wget -O $TMP_OUTPUT $SCHED_SPECIAL_URL && cat $TMP_OUTPUT >> $SCHED_LOG && rm $TMP_OUTPUT

exit 0

