#!/bin/sh

# PROJECT_DIR y BASE_URL deben establecerse antes de
# llamar el script en el cron

TMP_OUTPUT=/tmp/dumbu_scheduler

SCHED_URL=$BASE_URL/index.php/scheduler
SCHED_SPECIAL_URL=$BASE_URL/index.php/scheduler/special

SCHED_LOG=$PROJECT_DIR/var/messages.log

HTTP_PROXY=""
HTTPS_PROXY=""

SESSIONS_DIR=$PROJECT_DIR/vendor/mgp25/instagram-php/sessions/

/usr/bin/curl $SCHED_URL 2>/dev/null >> $SCHED_LOG
sleep 10
/usr/bin/curl $SCHED_SPECIAL_URL 2>/dev/null >> $SCHED_LOG

exit 0
